//! Each test is build as a separate ROM via `build.rs` but we still need to list all the test modules here,
//! or rust-analyzer will not pick up the tests and we will not get any error reporting in IDEs.

#![allow(non_snake_case)]

mod AiLengthRegisterMasking;
mod AiRegistersMirroring;
mod Cop0RegistersMasking;
mod CpuInstructionsLoadStore;
mod CpuInstructionsLogical;
mod CpuInstructionsShift;
mod Dummy;
mod MiMaskRegisterClearSet;
mod MiVersionRegisterValue;
mod PiRegistersMirroring;
mod RspDmaBuffering;
mod RspDmaFromRam;
mod RspDmaLatching;
mod RspMemoryMirroring;
mod RspRegistersMasking;
mod RspRegistersMirroring;
mod RspSemaphoreRegister;
mod ViRegistersMasking;

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/current_test.rs"));
