#![allow(non_snake_case)]

mod AiDma;
mod AiLengthRegisterMasking;
mod AiRegistersMirroring;
mod Cop0RegistersMasking;
mod CpuInstructionsArithmetic;
mod CpuInstructionsException;
mod CpuInstructionsLoadStore;
mod CpuInstructionsLogical;
mod CpuInstructionsShift;
mod Dummy;
mod MiMaskRegisterClearSet;
mod MiVersionRegisterValue;
mod PiRegistersMirroring;
mod RspDmaBuffering;
mod RspDmaFromRam;
mod RspDmaLatching;
mod RspMemoryMirroring;
mod RspRegistersMasking;
mod RspRegistersMirroring;
mod RspSemaphoreRegister;
mod ViRegistersMasking;

// Generated by build.rs
include!(concat!(env!("OUT_DIR"), "/plan.rs"));
